import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Days_One, Dongle, Bubbler_One } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const daysOne = Days_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-days-one",
});

const dongle = Dongle({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-dongle",
});

const bubblerOne = Bubbler_One({
  weight: "400",
  subsets: ["latin"],
  variable: "--font-bubbler-one",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link 
          rel="preload" 
          href="/fonts/dirtyline.otf" 
          as="font" 
          type="font/otf" 
          crossOrigin="anonymous"
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${daysOne.variable} ${dongle.variable} ${bubblerOne.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
